# Based on https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
name: Build Docs
permissions: write-all

on:
  push:
    branches:
      - muluna-2-prerelease
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.4
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: luarocks install --only-deps ldoc-dev-1.rockspec
    - name: Build docs
      run: ldoc .
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
