name: Release

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install release dependencies
        run: |
          npm install semantic-release@^24 \
          @semantic-release/git@^10 semantic-release-factorio@^1.5.1 \
          conventional-changelog-conventionalcommits@^8
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FACTORIO_TOKEN: ${{ secrets.FACTORIO_TOKEN }}


# Based on https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
name: Build Docs
on:
  push:
    branches:
      - muluna-2-prerelease
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.2
    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup dependencies
      run: luarocks install --only-deps ldoc-dev-1.rockspec
    - name: Build docs
      run: make doc-site
    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
